version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .${PROJECT}:${WORKSPACE_PROJECT}
    working_dir: ${WORKSPACE_PROJECT}
