version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/root/workspace
    environment:
      TZ: Asia/Tokyo
    working_dir: /root/workspace/Projects
    tty: true
